server:
  port: 5555

spring:
  application:
    name: 'api-gateway'

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "routes"

zuul:
  sensitive-headers:
    - Cookie, Authorization

api:
  registration:
    url:
      path: /auth/user
  login:
    url:
      path: /auth/auth/login

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: huhustttsb525353476ttrggsKLKHFHAS